const emailSettingsDb=getSupabase();
let emailSettingsCompanyId=null,emailSettingsRowId=null;
let emailMessageTimer=null;
const emailFields={emailNotifications:"emailnotifications",customerBookingEmails:"customer_booking_emails",officeNewBookingEmails:"office_new_booking_emails",driverAssignmentEmails:"driver_assignment_emails",bookingChangeEmails:"booking_change_emails",cancellationEmails:"cancellation_emails",paymentConfirmationEmails:"payment_confirmation_emails",unallocatedReminderEmails:"unallocated_reminder_emails",officeNotificationEmail:"office_notification_email",additionalOfficeRecipients:"additional_office_recipients",emailReplyTo:"email_reply_to",emailSenderName:"email_sender_name"};
document.addEventListener("DOMContentLoaded",async()=>{try{const context=await getAdminCompanyContext();emailSettingsCompanyId=context.companyId;await loadEmailSettings();await loadProviderStatus();document.getElementById("saveEmailSettings").onclick=saveEmailSettings;document.getElementById("sendTestEmail").onclick=sendTestEmail;}catch(error){showEmailMessage(error.message,true);}});
async function loadEmailSettings(){const columns=["id","company_id",...Object.values(emailFields),"unallocated_reminder_minutes"].join(",");const {data,error}=await emailSettingsDb.from("settings").select(columns).eq("company_id",emailSettingsCompanyId).maybeSingle();if(error)throw error;if(!data||String(data.company_id)!==String(emailSettingsCompanyId))throw new Error("Email settings are not accessible for this company.");emailSettingsRowId=data.id;for(const [id,column] of Object.entries(emailFields)){const element=document.getElementById(id);if(element.type==="checkbox")element.checked=data[column]!==false;else element.value=data[column]||"";}document.getElementById("unallocatedReminderMinutes").value=(data.unallocated_reminder_minutes||[2880,1440]).join(", ");}
async function saveEmailSettings(){const timings=parseTimings();if(!timings)return;const emails=validatedEmailSettings();if(!emails)return;const button=document.getElementById("saveEmailSettings");const originalText=button.textContent;button.disabled=true;button.textContent="Saving…";showEmailMessage("Saving email settings…");try{const update={unallocated_reminder_minutes:timings};for(const [id,column] of Object.entries(emailFields)){const element=document.getElementById(id);update[column]=element.type==="checkbox"?element.checked:(element.value.trim()||null);}Object.assign(update,emails);const {data,error}=await emailSettingsDb.from("settings").update(update).eq("id",emailSettingsRowId).eq("company_id",emailSettingsCompanyId).select("id,company_id").maybeSingle();if(error||!data)return showEmailMessage(error?.message||"Email settings could not be saved. No matching company settings row was updated.",true);showEmailMessage("Email settings saved successfully.",false,5000);}catch(error){showEmailMessage(error?.message||"Email settings could not be saved. Please try again.",true);}finally{button.disabled=false;button.textContent=originalText;}}
function validatedEmailSettings(){const fields=[["officeNotificationEmail","Office notification email"],["emailReplyTo","Reply-to email"]];const values={};for(const [id,label] of fields){const element=document.getElementById(id);const value=element.value.trim();if(value&&!isPlainEmail(value)){element.focus();showEmailMessage(`${label} must contain one email address only, for example bookings@example.com.`,true);return null;}values[emailFields[id]]=value||null;}const recipients=document.getElementById("additionalOfficeRecipients");const list=recipients.value.split(/[,;\n]+/).map(value=>value.trim()).filter(Boolean);const invalid=list.find(value=>!isPlainEmail(value));if(invalid){recipients.focus();showEmailMessage("Additional office recipients must be valid email addresses separated by commas.",true);return null;}const normalised=list.join(", ");recipients.value=normalised;values[emailFields.additionalOfficeRecipients]=normalised||null;return values;}
function isPlainEmail(value){return/^[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$/i.test(value);}
function parseTimings(){const values=[...new Set(document.getElementById("unallocatedReminderMinutes").value.split(",").map(value=>Number(value.trim())).filter(Number.isFinite))];if(!values.length||values.some(value=>!Number.isInteger(value)||value<=0||value>10080)){showEmailMessage("Reminder timings must be whole minutes between 1 and 10080.",true);return null;}return values.sort((a,b)=>b-a);}
async function loadProviderStatus(){const {data,error}=await emailSettingsDb.functions.invoke("send-booking-email",{body:{company_id:emailSettingsCompanyId,event:"provider_status"}});const element=document.getElementById("emailProviderStatus");if(error||!data?.ok){element.textContent="Provider status unavailable.";return;}element.textContent=data.configured?"Configured — secure server credentials are available.":"Not configured — add the provider API key and verified sender as Supabase secrets.";}
async function sendTestEmail(){const button=document.getElementById("sendTestEmail");button.disabled=true;showEmailMessage("Sending test email…");const {data,error}=await emailSettingsDb.functions.invoke("send-booking-email",{body:{company_id:emailSettingsCompanyId,event:"test",event_id:crypto.randomUUID()}});button.disabled=false;if(error||!data?.ok)return showEmailMessage(data?.error||error?.message||"Test email failed.",true);showEmailMessage("Test email sent.");}
function showEmailMessage(message,error=false,hideAfter=0){const element=document.getElementById("emailSettingsMessage");if(!element)return;if(emailMessageTimer){clearTimeout(emailMessageTimer);emailMessageTimer=null;}element.textContent=message;element.className=`email-save-message ${error?"is-error":"is-success"}`;element.hidden=false;if(hideAfter>0)emailMessageTimer=setTimeout(()=>{element.hidden=true;element.textContent="";emailMessageTimer=null;},hideAfter);}
