import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const service=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
type Row=Record<string,any>;

Deno.serve(async request=>{if(request.method==="OPTIONS")return new Response("ok",{headers:cors});if(request.method!=="POST")return reply({ok:false,error:"Method not allowed"},405);try{const body=await request.json();const auth=request.headers.get("authorization")||"";const userDb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await userDb.auth.getUser();if(!user||!user.email)throw new ApiError(401,"Customer login required");const company=await resolveCompany(String(body.company_code||""));const action=String(body.action||"");if(action==="claim")return reply(await claimBooking(user,company,body));const membership=await customerMembership(user.id,company.id);if(!membership)throw new ApiError(403,"No customer account is linked to this company");if(action==="list")return reply(await listBookings(company,membership));if(action==="profile")return reply(await profile(company,membership));if(action==="update_profile")return reply(await updateProfile(company,membership,body));if(action==="update_booking")return reply(await updateBooking(user,company,membership,body));if(action==="cancel_booking")return reply(await cancelBooking(user,company,membership,body));throw new ApiError(400,"Unknown customer portal action")}catch(error){const status=error instanceof ApiError?error.status:500;console.error("customer-portal",error);return reply({ok:false,error:status===500?"Unable to complete customer portal request":error instanceof Error?error.message:"Unexpected error"},status)}});

async function resolveCompany(code:string){const {data,error}=await service.from("companies").select("id,company_code,name,trading_name").eq("company_code",code.trim()).maybeSingle();if(error)throw error;if(!data)throw new ApiError(404,"Company not found");return data}
async function customerMembership(userId:string,companyId:string){const {data,error}=await service.from("customer_users").select("id,auth_user_id,company_id,customer_id").eq("auth_user_id",userId).eq("company_id",companyId).maybeSingle();if(error)throw error;return data}
async function claimBooking(user:Row,company:Row,body:Row){if(!user.email_confirmed_at)throw new ApiError(403,"Verify your email before claiming a booking");const token=String(body.claim_token||"");if(!token)throw new ApiError(400,"A secure booking claim is required");const tokenHash=await sha256(token);const {data:claim,error}=await service.from("booking_claim_tokens").select("*").eq("token_hash",tokenHash).eq("company_id",company.id).is("claimed_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(error)throw error;if(!claim||claim.email_normalized!==String(user.email).trim().toLowerCase())throw new ApiError(403,"This booking claim is invalid or expired");const {data:booking,error:bookingError}=await service.from("bookings").select("id,company_id,customer_id,email,customer_email").eq("id",claim.booking_id).eq("company_id",company.id).maybeSingle();if(bookingError)throw bookingError;if(!booking||![booking.email,booking.customer_email].some(value=>String(value||"").trim().toLowerCase()===claim.email_normalized))throw new ApiError(403,"The booking does not match this verified account");const existing=await customerMembership(user.id,company.id);if(existing&&String(existing.customer_id)!==String(booking.customer_id))throw new ApiError(409,"This login is already linked to a different customer record for this company");if(!existing){const inserted=await service.from("customer_users").insert({auth_user_id:user.id,company_id:company.id,customer_id:booking.customer_id});if(inserted.error)throw inserted.error}const now=new Date().toISOString();const used=await service.from("booking_claim_tokens").update({claimed_at:now,claimed_by:user.id}).eq("id",claim.id).is("claimed_at",null);if(used.error)throw used.error;await service.from("customer_booking_audit").insert({company_id:company.id,booking_id:booking.id,auth_user_id:user.id,action:"claim"});return{ok:true}}
async function ownedBooking(companyId:string,customerId:string,id:string){const {data,error}=await service.from("bookings").select("*").eq("id",id).eq("company_id",companyId).eq("customer_id",customerId).maybeSingle();if(error)throw error;if(!data)throw new ApiError(404,"Booking not found");return data}
async function listBookings(company:Row,membership:Row){const {data,error}=await service.from("bookings").select("id,booking_reference,journey_date,journey_time,pickup_address,dropoff_address,airport,flight_number,passengers,suitcases,hand_luggage,vehicle_tier,vehicle_type,price,journey_fare,card_booking_fee_amount,payment_method,payment_status,amount_paid,balance_due,status,return_journey,return_date,return_time,cancelled_at,cancellation_reason,created_at,dispatched_at,accepted_at,on_way_at,passenger_onboard_at,completed_at,no_show_at").eq("company_id",company.id).eq("customer_id",membership.customer_id).order("journey_date",{ascending:false});if(error)throw error;const bookings=data||[],ids=bookings.map(row=>row.id);let stops:Row[]=[];if(ids.length){const result=await service.from("booking_stops").select("booking_id,stop_order,formatted_address").eq("company_id",company.id).in("booking_id",ids).order("stop_order");if(result.error)throw result.error;stops=result.data||[]}return{ok:true,company,bookings:bookings.map(row=>({...row,booking_stops:stops.filter(stop=>stop.booking_id===row.id)}))}}
async function profile(company:Row,membership:Row){const {data,error}=await service.from("customers").select("id,full_name,email,phone").eq("id",membership.customer_id).eq("company_id",company.id).maybeSingle();if(error)throw error;return{ok:true,customer:data}}
async function updateProfile(company:Row,membership:Row,body:Row){const name=clean(body.name);if(!name||name.length>160)throw new ApiError(400,"A valid name is required");const phone=clean(body.phone);if(phone&&phone.length>40)throw new ApiError(400,"Phone number is too long");const patch={full_name:name,phone};const {error}=await service.from("customers").update(patch).eq("id",membership.customer_id).eq("company_id",company.id);if(error)throw error;return{ok:true}}
async function updateBooking(user:Row,company:Row,membership:Row,body:Row){const booking=await ownedBooking(company.id,membership.customer_id,String(body.booking_id||""));if(String(booking.payment_status||"").toLowerCase()==="paid")throw new ApiError(409,"Please contact us to change this paid booking.");if(["accepted","on_way","passenger_onboard","completed","cancelled","no_show"].includes(String(booking.status||"").toLowerCase()))throw new ApiError(409,"This booking can no longer be changed online.");const changes=body.changes;if(!changes||typeof changes!=="object"||Array.isArray(changes))throw new ApiError(400,"Invalid booking changes");if(["pickup_address","dropoff_address","vehicle_tier","vehicle_type","return_journey"].some(key=>key in changes))throw new ApiError(409,"Please contact us for route, vehicle or return-journey changes so the fare can be recalculated safely.");const allowed:Row={};if(changes.journey_date!=null)allowed.journey_date=validDate(changes.journey_date);if(changes.journey_time!=null)allowed.journey_time=validTime(changes.journey_time);if(changes.passengers!=null){const passengers=Number(changes.passengers);const capacity:{[key:string]:number}={standard:4,car:4,executive_car:4,"5_7":7,mpv:7,executive_5_7:7,"5_8":8,"9_16":16,"17_23":23,"24_52":52};if(!Number.isInteger(passengers)||passengers<1||passengers>(capacity[booking.vehicle_tier||booking.vehicle_type]||0))throw new ApiError(400,"Passenger count exceeds the selected vehicle capacity");allowed.passengers=passengers}for(const key of ["suitcases","hand_luggage"]){if(key in changes){const value=Number(changes[key]);if(!Number.isInteger(value)||value<0||value>100)throw new ApiError(400,"Invalid luggage quantity");allowed[key]=value}}if("flight_number" in changes)allowed.flight_number=String(changes.flight_number||"").trim().slice(0,40)||null;if(allowed.journey_date||allowed.journey_time){const settings=await service.from("settings").select("minimumnotice,maxadvancedays").eq("company_id",company.id).maybeSingle();if(settings.error)throw settings.error;const when=new Date(`${allowed.journey_date||booking.journey_date}T${allowed.journey_time||booking.journey_time}`);const min=Math.max(0,Number(settings.data?.minimumnotice||0))*60000,max=Math.max(0,Number(settings.data?.maxadvancedays||365))*86400000;if(!Number.isFinite(when.valueOf())||when.valueOf()<Date.now()+min||when.valueOf()>Date.now()+max)throw new ApiError(400,"The requested date/time is outside the permitted booking window")}const result=await service.from("bookings").update(allowed).eq("id",booking.id).eq("company_id",company.id).eq("customer_id",membership.customer_id);if(result.error)throw result.error;await audit(user,company,booking,"change",allowed);await Promise.all([invokeInternal("send-booking-email",{company_id:company.id,booking_id:booking.id,event:"booking_changed"}),invokeInternal("google-calendar-sync",{company_id:company.id,booking_id:booking.id})]);return{ok:true}}
async function cancelBooking(user:Row,company:Row,membership:Row,body:Row){const booking=await ownedBooking(company.id,membership.customer_id,String(body.booking_id||""));if(String(booking.payment_status||"").toLowerCase()==="paid")throw new ApiError(409,"Please contact us to cancel this paid booking.");const settings=await service.from("settings").select("customercancel").eq("company_id",company.id).maybeSingle();if(settings.error)throw settings.error;if(!settings.data?.customercancel)throw new ApiError(403,"Online cancellation is not enabled. Please contact us.");if(["accepted","on_way","passenger_onboard","completed","cancelled","no_show"].includes(String(booking.status||"").toLowerCase()))throw new ApiError(409,"This booking can no longer be cancelled online.");const patch={status:"cancelled",booking_status:"cancelled",cancelled_at:new Date().toISOString(),cancelled_by:`customer:${user.id}`,cancellation_reason:String(body.reason||"").trim().slice(0,500)||null};const result=await service.from("bookings").update(patch).eq("id",booking.id).eq("company_id",company.id).eq("customer_id",membership.customer_id);if(result.error)throw result.error;await audit(user,company,booking,"cancel",patch);await Promise.all([invokeInternal("send-booking-email",{company_id:company.id,booking_id:booking.id,event:"booking_cancelled"}),invokeInternal("google-calendar-sync",{company_id:company.id,booking_id:booking.id})]);return{ok:true,message:"Booking cancelled."}}
async function audit(user:Row,company:Row,booking:Row,action:string,changes:Row){const result=await service.from("customer_booking_audit").insert({company_id:company.id,booking_id:booking.id,auth_user_id:user.id,action,changes});if(result.error)throw result.error}
async function invokeInternal(name:string,body:Row){const base=String(Deno.env.get("SUPABASE_URL")||""),key=String(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");if(!base||!key)return;try{const response=await fetch(`${base}/functions/v1/${name}`,{method:"POST",headers:{"Content-Type":"application/json",apikey:key,Authorization:`Bearer ${key}`},body:JSON.stringify(body)});if(!response.ok)console.error("Customer portal follow-up failed",{name,status:response.status})}catch(error){console.error("Customer portal follow-up failed",{name,error:error instanceof Error?error.message:error})}}
const clean=(value:unknown)=>String(value??"").trim()||null;
function validDate(value:unknown){const text=String(value||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(text))throw new ApiError(400,"Invalid date");return text}
function validTime(value:unknown){const text=String(value||"");if(!/^\d{2}:\d{2}(:\d{2})?$/.test(text))throw new ApiError(400,"Invalid time");return text}
async function sha256(value:string){const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return [...bytes].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
